export { default as EmpleadoTooltips } from './EmpleadoTooltips.vue'
export { default as EmpleadoListTooltips } from './EmpleadoListTooltips.vue'
export { default as EmpresaTooltips } from './EmpresaTooltips.vue'
export { default as ParametrizacionTooltips } from './ParametrizacionTooltips.vue'
export { default as PrenominaTooltips } from './PrenominaTooltips.vue'
export { default as CuentaTooltips } from './CuentaTooltips.vue'
