export interface EmpleadoModel {
  id: number
  id_nomina_gape_empresa?: number
  idempleado?: number
  estado_empleado?: boolean
  iddepartamento?: number
  idpuesto?: number
  idtipoperiodo?: number
  idturno?: number
  codigoempleado?: string
  nombre?: string
  apellidopaterno?: string
  apellidomaterno?: string
  nombrelargo?: string
  fechanacimiento?: Date
  lugarnacimiento?: string
  estadocivil?: string
  sexo?: string
  curpi?: string
  curpf?: string
  numerosegurosocial?: string
  umf?: number
  rfc?: string
  homoclave?: string
  cuentapagoelectronico?: string
  sucursalpagoelectronico?: string
  bancopagoelectronico?: string
  estadoempleado?: string
  sueldodiario?: number
  fechasueldodiario?: Date
  sueldovariable?: number
  fechasueldovariable?: Date
  sueldopromedio?: number
  fechasueldopromedio?: Date
  sueldointegrado?: number
  fechasueldointegrado?: Date
  calculado: boolean
  afectado: boolean
  calculadoextraordinario: boolean
  afectadoextraordinario?: boolean
  interfazcheqpaqw: boolean
  modificacionneto: boolean
  fechaalta?: Date
  cuentacw?: string
  tipocontrato?: string
  basecotizacionimss?: string
  tipoempleado?: string
  basepago?: string
  formapago?: string
  zonasalario?: string
  calculoptu: boolean
  calculoaguinaldo: boolean
  modificacionsalarioimss: boolean
  altaimss: boolean
  bajaimss: boolean
  cambiocotizacionimss: boolean
  expediente?: string
  telefono?: string
  codigopostal?: string
  direccion?: string
  poblacion?: string
  estado_emp?: string
  nombrepadre?: string
  nombremadre?: string
  numeroafore?: string
  fechabaja?: Date
  causabaja?: string
  sueldobaseliquidacion?: number
  campoextra1?: string
  campoextra2?: string
  campoextra3?: string
  fechareingreso?: Date
  ajustealneto?: number
  timestamp?: Date
  cidregistropatronal?: number
  ccampoextranumerico1?: number
  ccampoextranumerico2?: number
  ccampoextranumerico3?: number
  ccampoextranumerico4?: number
  ccampoextranumerico5?: number
  cestadoempleadoperiodo?: string
  cfechasueldomixto?: Date
  csueldomixto?: number
  NumeroFonacot?: string
  CorreoElectronico?: string
  TipoRegimen?: string
  ClabeInterbancaria?: string
  EntidadFederativa?: string
  Subcontratacion: boolean
  ExtranjeroSinCURP: boolean
  TipoPrestacion?: number
  DiasVacTomadasAntesdeAlta: number
  DiasPrimaVacTomadasAntesdeAlta: number
  TipoSemanaReducida?: number
  Teletrabajador: number
  Equipo?: string
  Insumo?: string
  DireccionTeletrabajo?: string
  carga_masiva?: boolean
  estado?: string
  curpCompleto?: string
  id_nomina_gape_cliente?: number | null
  fiscal: boolean
  fecha_alta_gape?: string
  sueldo_real?: number
  sueldo_imss_gape?: number
}
