export interface EmpresaModel {
  idcptoprimavac: number
  idcptoaguinaldo: number
  idcptoptu: number
  idcptovacaciones: number
  nombrecorto: string
  rutarespaldo: string
  rutacontpaqw: string
  rutacheqpaqw: string
  idempresacontpaqw: number
  direccion: string
  telefono1: string
  telefono2: string
  telefono3: string
  fax: string
  registroimss: string
  registrocamara: string
  rfc: string
  homoclave: string
  registroinfonavit: string
  registrofonacot: string
  registrocomisionmixta: string
  registrossa: string
  zonasalariogeneral: string
  fechainiciohistoria: string
  fechaconstitucion: string
  ejercicio: number
  porcentajesubsidio: number
  cuentacwglobal: string
  estructuracuentacw: string
  formatosobrerecibo: string
  afectarperiodosanteriores: boolean
  afectarperiodosfuturos: boolean
  posicioncuentaempleado: number
  longitudcuentaempleado: number
  posicioncuentadepto: number
  longitudcuentadepto: number
  localidad: string
  nombrerepresentante: string
  appaternorepresentante: string
  apmaternorepresentante: string
  codigopostal: string
  apartadopostal: string
  mascarillacodigo: string
  numerodecimales: number
  tipocodigoempleado: string
  mostraragenda: boolean
  timestamp: string
  idcptoajuste: number
  idcptoindem20: number
  idcptoindem90: number
  idcptoprimaantig: number
  idcptoprimavacrep: number
  idcptosueldo: number
  idcptovacrep: number
  FactorNoDeducExento: number
  GUIDEmpresa: string
  GUIDDSL: string
  EmitirRecibo: boolean
  RegimenFiscal: string
  OrigenDSL: string
  FormatoSobreReciboCFDI: string
  CURP: string
  vConfigComprobante: string
  vUltTimbreComprobante: string
  vConfigComplemento: string
  vUltTimbreComplemento: string
  OrigenRecursos: string
  contratista: boolean
  DatosVigente: boolean
  RelacionarCFDI: boolean
  GUIDEmpresaOrigen: string
  EditarFechaPago: boolean
  FiniquitoDividido: boolean
  TipoCalculoISR: string
  NombreEmpresaFiscal: string
  CriterioPrestacion: string
  GUIDColabora: string
}
