import type { SATCatClaveEntidadFederativaModel } from '@/interfaces/nomina/nomGenerales/SATCatClaveEntidadFederativa'

export function getDefaultSATCatClaveEntidadFederativa(): SATCatClaveEntidadFederativaModel[] {
  return [
    { Codigo: 'AS', Descripcion: 'AGUASCALIENTES' },
    { Codigo: 'BC', Descripcion: 'BAJA CALIFORNIA' },
    { Codigo: 'BS', Descripcion: 'BAJA CALIFORNIA SUR' },
    { Codigo: 'CC', Descripcion: 'CAMPECHE' },
    { Codigo: 'CL', Descripcion: 'COAHUILA' },
    { Codigo: 'CM', Descripcion: 'COLIMA' },
    { Codigo: 'CS', Descripcion: 'CHIAPAS' },
    { Codigo: 'CH', Descripcion: 'CHIHUAHUA' },
    { Codigo: 'DF', Descripcion: 'CIUDAD DE MÉXICO' },
    { Codigo: 'DG', Descripcion: 'DURANGO' },
    { Codigo: 'GT', Descripcion: 'GUANAJUATO' },
    { Codigo: 'GR', Descripcion: 'GUERRERO' },
    { Codigo: 'HG', Descripcion: 'HIDALGO' },
    { Codigo: 'JC', Descripcion: 'JALISCO' },
    { Codigo: 'MC', Descripcion: 'MÉXICO' },
    { Codigo: 'MN', Descripcion: 'MICHOACÁN' },
    { Codigo: 'MS', Descripcion: 'MORELOS' },
    { Codigo: 'NT', Descripcion: 'NAYARIT' },
    { Codigo: 'NL', Descripcion: 'NUEVO LEÓN' },
    { Codigo: 'OC', Descripcion: 'OAXACA' },
    { Codigo: 'PL', Descripcion: 'PUEBLA' },
    { Codigo: 'QT', Descripcion: 'QUERÉTARO' },
    { Codigo: 'QR', Descripcion: 'QUINTANA ROO' },
    { Codigo: 'SP', Descripcion: 'SAN LUIS POTOSÍ' },
    { Codigo: 'SL', Descripcion: 'SINALOA' },
    { Codigo: 'SR', Descripcion: 'SONORA' },
    { Codigo: 'TC', Descripcion: 'TABASCO' },
    { Codigo: 'TS', Descripcion: 'TAMAULIPAS' },
    { Codigo: 'TL', Descripcion: 'TLAXCALA' },
    { Codigo: 'VZ', Descripcion: 'VERACRUZ' },
    { Codigo: 'YN', Descripcion: 'YUCATÁN' },
    { Codigo: 'ZS', Descripcion: 'ZACATECAS' },
    { Codigo: 'NE', Descripcion: 'NACIDO EN EL EXTRANJERO' },
  ]
}
