export interface NominaEmpresaModel {
  NombreEmpresa: string
  IDEmpresa: number
  IDCptoPrimaVac?: number
  IDCptoAguinaldo?: number
  IDCptoPTU?: number
  IDCptoVacaciones?: number
  NombreCorto?: string
  RutaEmpresa?: string
  RutaRespaldo?: string
  RutaContpaqW?: string
  RutaCheqpaqW?: string
  IDEmpresaContpaqW?: number
  Direccion?: string
  Telefono1?: string
  Telefono2?: string
  Telefono3?: string
  Fax?: string
  RegistroIMSS?: string
  RegistroCamara?: string
  RFC?: string
  Homoclave?: string
  RegistroInfonavit?: string
  RegistroFonacot?: string
  RegistroComisionMixta?: string
  RegistroSSA?: string
  ZonaSalarioGeneral?: string
  FechaInicioHistoria?: Date
  FechaConstitucion?: Date
  Ejercicio?: number
  PorcentajeSubsidio?: number
  CuentaCWGlobal?: string
  EstructuraCuentaCW?: string
  FormatoSobreRecibo?: string
  AfectarPeriodosAnteriores: boolean
  AfectarPeriodosFuturos: boolean
  PosicionCuentaEmpleado?: number
  LongitudCuentaEmpleado?: number
  PosicionCuentaDepto?: number
  LongitudCuentaDepto?: number
  Localidad?: string
  NombreRepresentante?: string
  ApPaternoRepresentante?: string
  ApMaternoRepresentante?: string
  CodigoPostal?: string
  ApartadoPostal?: string
  MascarillaCodigo?: string
  NumeroDecimales?: number
  TipoCodigoEmpleado?: string
  MostrarAgenda: boolean
  TimeStamp?: Date
  IDCptoAjuste?: number
  IDCptoIndem20?: number
  IDCptoIndem90?: number
  IDCptoPrimaAntig?: number
  IDCptoPrimaVacRep?: number
  IDCptoSueldo?: number
  IDCptoVacRep?: number
  FactorNoDeducExento?: number
  GUIDEmpresa: string
  GUIDDSL: string
  EmitirRecibo?: number
  RegimenFiscal?: string
  OrigenDSL?: number
  FormatoSobreReciboCFDI: string
  CURP: string
  vConfigComprobante: string
  vUltTimbreComprobante: string
  vConfigComplemento: string
  vUltTimbreComplemento: string
  OrigenRecursos: string
  contratista: boolean
  DatosVigente: boolean
  RelacionarCFDI: string
  GUIDEmpresaOrigen: string
  EditarFechaPago: boolean
  FiniquitoDividido: boolean
  TipoCalculoISR: number
  NombreEmpresaFiscal: string
  CriterioPrestacion: number
  GUIDColabora: string
}
